NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 0.0
NDefines.NMilitary.UNIT_LEADER_ASSIGN_TRAIT_COST = 0.0




-- NDefines.NSupply.SUPPLY_PATH_MAX_DISTANCE = 0.0
-- NDefines.NSupply.RAILWAY_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
-- NDefines.NSupply.TRUCK_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
-- NDefines.NSupply.NAVAL_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0

NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 10000.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 10000.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 0.25


NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.0

NDefines.NMilitary.UNIT_LEADER_USE_NONLINEAR_XP_GAIN = false

NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.9

NDefines.NMilitary.CONSTANT_XP_RATIO_FOR_MULTIPLE_LEADERS_IN_SAME_COMBAT = 0.0



NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 100.0
NDefines.NDiplomacy.VOLUNTEERS_RETURN_EQUIPMENT = 1.0
NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 1
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 0

NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.0

COMBAT_LOG_MAX_MONTHS = 6






NDefines.NAI.MAX_AHEAD_RESEARCH_PENALTY = 100.0





NDefines.NCountry.FUEL_LEASE_CONVOY_RATIO = 0.0