NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 0.0
NDefines.NMilitary.UNIT_LEADER_ASSIGN_TRAIT_COST = 0.0




-- NDefines.NSupply.SUPPLY_PATH_MAX_DISTANCE = 0.0
-- NDefines.NSupply.RAILWAY_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
-- NDefines.NSupply.TRUCK_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
-- NDefines.NSupply.NAVAL_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0

NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 10000.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 10000.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 0.25


NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.0

NDefines.NMilitary.UNIT_LEADER_USE_NONLINEAR_XP_GAIN = false




NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 100.0
NDefines.NDiplomacy.VOLUNTEERS_RETURN_EQUIPMENT = 1.0
NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 1
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 0

NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.0