NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 0.0
NDefines.NMilitary.UNIT_LEADER_ASSIGN_TRAIT_COST = 0.0




-- NDefines.NSupply.SUPPLY_PATH_MAX_DISTANCE = 0.0
-- NDefines.NSupply.RAILWAY_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
-- NDefines.NSupply.TRUCK_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0
-- NDefines.NSupply.NAVAL_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.0

NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 10000.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 10000.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 0.25